// apps/desktop/src/App.vue
<script setup lang="ts">
// App.vue mounts and provides. It holds no state machine and coordinates
// nothing (SPEC 9.10); a gate fails the build past 120 lines.

import { listen } from "@tauri-apps/api/event";
import { onMounted, ref, watch } from "vue";
import { unwrap } from "./bridge";
import { scheduleFrame } from "./frame-scheduler";
import { commands } from "./generated/bindings.gen";
import Workbench from "./shell/Workbench.vue";
import { applyTypography } from "./typography";
import "./app.css";
import "./fonts.css";
import "./themes.css";

const theme = ref("tou");

// The generated selectors live on :root[data-theme]; the shell element is
// not :root. One projection, one direction (INV-15).
watch(
  theme,
  (next) => {
    document.documentElement.dataset.theme = next;
  },
  { immediate: true },
);

const applyConfig = async (): Promise<void> => {
  try {
    const snapshot = await unwrap(commands.readConfig());
    const appearance = snapshot.config.appearance;
    theme.value = appearance.theme;
    scheduleFrame("appearance", () => {
      document.documentElement.dataset.paper = appearance.paper;
      applyTypography(document.documentElement, appearance.typography);
    });
  } catch {
    // A damaged Config is the Settings surface's story to tell, not a reason
    // the author cannot write today (SPEC 10.1).
  }
};

onMounted(async () => {
  await listen("config-changed", () => void applyConfig());
  await applyConfig();
});
</script>

<template>
  <main class="shell">
    <Workbench @theme-changed="(next: string) => (theme = next)" />
  </main>
</template>

<style>
.shell {
  min-height: 100vh;
  background: var(--paper);
  color: var(--ink);
}
</style>

// apps/desktop/src/App.tsx
/* App mounts and provides. It holds no state machine and coordinates nothing
   (SPEC 9.10); a gate fails the build past 120 lines. */

import { listen } from "@tauri-apps/api/event";
import { createEffect, createSignal, onMount } from "solid-js";
import { unwrap } from "./bridge";
import { scheduleFrame } from "./frame-scheduler";
import { commands } from "./generated/bindings.gen";
import { Workbench } from "./shell/Workbench";
import { applyTypography } from "./typography";

export function App() {
  const [theme, setTheme] = createSignal("tou");

  // The generated selectors live on :root[data-theme]; the shell element is
  // not :root. One projection, one direction (INV-15).
  createEffect(() => {
    document.documentElement.dataset.theme = theme();
  });

  const applyConfig = async (): Promise<void> => {
    try {
      const snapshot = await unwrap(commands.readConfig());
      const appearance = snapshot.config.appearance;
      if (appearance === undefined) return;
      setTheme(appearance.theme);
      scheduleFrame("appearance", () => {
        document.documentElement.dataset.paper = appearance.paper;
        applyTypography(document.documentElement, appearance.typography);
      });
    } catch {
      // A damaged Config is the Settings surface's story to tell, not a reason
      // the author cannot write today (SPEC 10.1).
    }
  };

  onMount(async () => {
    await listen("config-changed", () => void applyConfig());
    await applyConfig();
  });

  return (
    <main class="shell">
      <Workbench onThemeChanged={setTheme} />
    </main>
  );
}
