// apps/desktop/src/ui/EditorHost.tsx
// The only module that mounts packages/editor (SPEC 9.10). It translates the
// adapter's changes into bridge DTOs and the domain's confirmations back into
// projection updates. It holds no state machine; the queue it keeps is the
// bounded pending-action queue of SPEC 7.2-5.

import {
  type EditorAction,
  type EditorAnnotationProjection,
  type EditorContext,
  type EditorDocument,
  type EditorFormat,
  type EditorHandle,
  mountEditor,
  type PunctuationFinding,
} from "@refrain/editor";
import { createEffect, onCleanup, onMount } from "solid-js";
import { describe, unwrap } from "../bridge";
import { EditorActionQueue } from "../editor-host/editor-action-queue";
import { cancelScheduledFrame, scheduleFrame } from "../frame-scheduler";
import {
  commands,
  type EditorChangeDto,
  type OpenDocumentDto_Serialize,
} from "../generated/bindings.gen";

/**
 * What the shell may ask of the open editor.
 *
 * Vue exposed these through `defineExpose`, which let any parent reach in by
 * name. Naming the surface as a type makes the seam checkable: the shell can
 * only call what appears here.
 */
export interface EditorHostHandle {
  focus(): void;
  isComposing(): boolean;
  caret(): { blockId: string; offset: number } | null;
  formatSelection(kind: EditorFormat): boolean;
  deleteEmptyBlock(): boolean;
  applyPunctuation(finding: PunctuationFinding): boolean;
  /** Resolve once no composition is in flight — an event, never a timer. */
  whenSettled(): Promise<void>;
  /** Resolve after the pending-action queue fully drains. */
  settled(): Promise<void>;
}

export interface EditorHostProps {
  readonly rootId: string;
  readonly path: string;
  readonly document: OpenDocumentDto_Serialize;
  readonly annotations: readonly EditorAnnotationProjection[];
  readonly onConfirmed: (revision: string) => void;
  readonly onRejected: (reason: string) => void;
  readonly onContext: (context: EditorContext, pointerX: number, pointerY: number) => void;
  /** Receives the handle on mount and null on teardown. */
  readonly onReady: (handle: EditorHostHandle | null) => void;
}

const toDto = (action: EditorAction): EditorChangeDto[] =>
  action.changes.map((change) =>
    change.kind === "replace"
      ? { kind: "replace", value: { blocks: [...change.blocks], text: change.text } }
      : { kind: "insert", value: { before: change.before, texts: [...change.texts] } },
  );

export function EditorHost(props: EditorHostProps) {
  let host: HTMLDivElement | undefined;
  let editor: EditorHandle | null = null;
  let confirmedRevision = props.document.revision;
  const confirmationFrame = `editor-confirm:${props.rootId}:${props.path}`;

  const apply = async (action: EditorAction): Promise<void> => {
    const structural = action.changes.some(
      (change) =>
        (change.kind === "replace" && (change.text === null || change.blocks.length > 1)) ||
        change.kind === "insert",
    );
    const transition = await unwrap(
      commands.applyEditorAction(props.rootId, props.path, {
        base: confirmedRevision,
        changes: toDto(action),
      }),
    );
    confirmedRevision = transition.revision;
    editor?.setRevision(transition.revision);
    if (structural) {
      const confirmed = await unwrap(commands.currentDocument(props.rootId, props.path));
      editor?.replace({ revision: confirmed.revision, blocks: confirmed.blocks });
      editor?.focus();
    }
    props.onConfirmed(transition.revision);
  };

  const actions = new EditorActionQueue(
    apply,
    (task) => scheduleFrame(confirmationFrame, task),
    (error) => props.onRejected(describe(error)),
  );

  const onContextMenu = (event: MouseEvent): void => {
    // Candidate text is not settled manuscript text: refuse rather than act
    // on characters the author has not chosen yet.
    if (editor?.isComposing()) {
      event.preventDefault();
      return;
    }
    const context = editor?.context(event.target);
    if (context === null || context === undefined) return;
    event.preventDefault();
    props.onContext(context, event.clientX, event.clientY);
  };

  onMount(() => {
    if (host === undefined) return;
    const document: EditorDocument = {
      revision: props.document.revision,
      blocks: props.document.blocks,
    };
    editor = mountEditor(host, document, { submit: (action) => actions.submit(action) });
    editor.setAnnotations(props.annotations);
    editor.focus();
    props.onReady({
      focus: () => editor?.focus(),
      isComposing: () => editor?.isComposing() ?? false,
      caret: () => editor?.caret() ?? null,
      formatSelection: (kind) => editor?.formatSelection(kind) ?? false,
      deleteEmptyBlock: () => editor?.deleteEmptyBlock() ?? false,
      applyPunctuation: (finding) => editor?.applyPunctuation(finding) ?? false,
      whenSettled: async () => {
        await editor?.whenSettled();
      },
      settled: async () => {
        await editor?.whenSettled();
        await actions.settled();
      },
    });
  });

  createEffect(() => {
    editor?.setAnnotations(props.annotations);
  });

  onCleanup(() => {
    props.onReady(null);
    actions.destroy();
    cancelScheduledFrame(confirmationFrame);
    editor?.destroy();
    editor = null;
  });

  return (
    <div class="editor-wrap">
      {/* The editor owns focus through its contenteditable paragraph descendants. */}
      {/* biome-ignore lint/a11y/noStaticElementInteractions: custom editor event boundary */}
      <div ref={host} class="editor-host" data-testid="editor-host" onContextMenu={onContextMenu} />
      <div class="hashira" aria-hidden="true">
        {props.path}
      </div>
    </div>
  );
}

// apps/desktop/src/editor-host/EditorHost.vue
<script setup lang="ts">
// The only module that mounts packages/editor (SPEC 9.10). It translates the
// adapter's changes into bridge DTOs and the domain's confirmations back into
// projection updates. It holds no state machine; the queue it keeps is the
// bounded pending-action queue of SPEC 7.2-5.

import {
  type EditorAction,
  type EditorDocument,
  type EditorHandle,
  mountEditor,
} from "@refrain/editor";
import { onBeforeUnmount, onMounted, ref } from "vue";
import { describe, unwrap } from "../bridge";
import {
  commands,
  type EditorChangeDto,
  type OpenDocumentDto_Serialize,
} from "../generated/bindings.gen";

const props = defineProps<{
  rootId: string;
  path: string;
  document: OpenDocumentDto_Serialize;
}>();

const emit = defineEmits<{
  confirmed: [revision: string];
  rejected: [reason: string];
}>();

const host = ref<HTMLElement | null>(null);
let editor: EditorHandle | null = null;
// Confirmed-domain base for the next action: actions chain base → revision.
let confirmedRevision = props.document.revision;
// The bounded pending-action queue (SPEC 7.2-5): settles land here, one apply
// crosses the bridge at a time, and a save waits for the queue to drain.
// Without it two rapid settles race on the same base and all but the first
// are refused as stale — which is how typed characters once vanished.
let inFlight = false;
const queue: EditorAction[] = [];
const settled: { resolve: (() => void)[] } = { resolve: [] };

const toDto = (action: EditorAction): EditorChangeDto[] =>
  action.changes.map((change) =>
    change.kind === "replace"
      ? { kind: "replace", value: { blocks: [...change.blocks], text: change.text } }
      : {
          kind: "insert",
          value: { before: change.before, texts: [...change.texts] },
        },
  );

/** A typing burst on one block coalesces into one action. */
const tryMerge = (action: EditorAction): boolean => {
  const last = queue.at(-1);
  const only = action.changes.length === 1 ? action.changes[0] : undefined;
  const prev = last?.changes.length === 1 ? last.changes[0] : undefined;
  if (
    last === undefined ||
    only?.kind !== "replace" ||
    prev?.kind !== "replace" ||
    only.text === null ||
    prev.text === null ||
    only.blocks.length !== 1 ||
    prev.blocks.length !== 1 ||
    only.blocks[0] !== prev.blocks[0]
  ) {
    return false;
  }
  queue[queue.length - 1] = {
    baseRevision: last.baseRevision,
    changes: [{ kind: "replace", blocks: prev.blocks, text: only.text }],
  };
  return true;
};

const drain = async (): Promise<void> => {
  if (inFlight) return;
  const action = queue.shift();
  if (action === undefined) {
    for (const resolve of settled.resolve.splice(0)) resolve();
    return;
  }
  inFlight = true;
  const structural = action.changes.some(
    (change) =>
      (change.kind === "replace" && (change.text === null || change.blocks.length > 1)) ||
      change.kind === "insert",
  );
  try {
    const transition = await unwrap(
      commands.applyEditorAction(props.rootId, props.path, {
        base: confirmedRevision,
        changes: toDto(action),
      }),
    );
    confirmedRevision = transition.revision;
    editor?.setRevision(transition.revision);
    if (structural) {
      const confirmed = await unwrap(commands.currentDocument(props.rootId, props.path));
      editor?.replace({ revision: confirmed.revision, blocks: confirmed.blocks });
      editor?.focus();
    }
    emit("confirmed", transition.revision);
  } catch (error) {
    emit("rejected", describe(error));
  } finally {
    inFlight = false;
    void drain();
  }
};

const submit = (action: EditorAction): void => {
  if (!tryMerge(action)) queue.push(action);
  void drain();
};

onMounted(() => {
  if (!host.value) return;
  const document: EditorDocument = {
    revision: props.document.revision,
    blocks: props.document.blocks,
  };
  editor = mountEditor(host.value, document, { submit });
  editor.focus();
});

onBeforeUnmount(() => {
  editor?.destroy();
  editor = null;
});

defineExpose({
  isComposing: () => editor?.isComposing() ?? false,
  caret: () => editor?.caret() ?? null,
  /** Resolves when the pending-action queue has fully drained (SPEC 7.2-5). */
  settled: (): Promise<void> =>
    queue.length === 0 && !inFlight
      ? Promise.resolve()
      : new Promise<void>((resolve) => {
          settled.resolve.push(resolve);
        }),
});
</script>

<template>
  <div ref="host" class="editor-host" data-testid="editor-host" />
</template>

<style>
.editor-host {
  max-width: 680px;
  margin: 0 auto;
  padding: 48px 24px;
  line-height: 1.75;
  font-size: 17px;
  font-family: var(--manuscript-family, serif);
}

.editor-host p[data-block-id] {
  cursor: text;
  caret-color: var(--ink);
}
</style>
