// apps/desktop/src/ui/DispatchSurface.tsx
// 派发界面（SPEC 9.6）：读 DispatchSession 的投影，把点击译成意图。
//
// 这里没有业务分支，没有跨桥调用，也没有「先怎样再怎样」的次序——那些都在
// shell/dispatch-session.ts 里，并且在没有浏览器的情况下被测试。这个文件只回答
// 一个问题：当下这份 view 应该长什么样。
import {
  createEffect,
  createMemo,
  createSignal,
  For,
  type JSX,
  onCleanup,
  onMount,
  Show,
} from "solid-js";

import { describe } from "../bridge";
import type { BlockDto, CarryMode, DocumentRow } from "../generated/bindings.gen";
import {
  browserDispatchGateway,
  type Copies,
  type DispatchMaterial,
  DispatchSession,
  editingDraftId,
  runStatusLabel,
  terminal,
  tokenLabel,
} from "../shell/dispatch-session";

export type { DispatchMaterial } from "../shell/dispatch-session";

export type DispatchSurfaceProps = {
  rootId: string;
  path: string;
  blocks: BlockDto[];
  materials: DispatchMaterial[];
  /** Block ids planted by the editor's context menu (派发此段 / 加入派发). */
  seed?: string[];
  /** A persisted author-comment packet converted into a normal dispatch ticket. */
  initialPrompt?: string;
  onCollected?: (count: number) => void;
  onMaterialSaved?: (row: DocumentRow) => void;
  onClosed?: () => void;
};

/** 在途单子的回看间隔。够快让作者察觉，够慢不至于让一份摊开的稿子一直在过桥。 */
const POLL_INTERVAL_MS = 2_500;

export function DispatchSurface(props: DispatchSurfaceProps): JSX.Element {
  const session = new DispatchSession(
    browserDispatchGateway,
    {
      rootId: props.rootId,
      path: props.path,
      blocks: props.blocks,
      materials: props.materials,
    },
    {
      collected: (count) => props.onCollected?.(count),
      materialSaved: (row) => props.onMaterialSaved?.(row),
    },
    describe,
  );

  // 一个信号承载整份 view。session 每次广播换一个引用，Solid 据此重算读到它的部分。
  const [view, setView] = createSignal(session.view());
  onCleanup(session.onChanged(() => setView(session.view())));

  const model = () => view().model;
  const cells = () => view().cells;
  const runs = () => view().runs;
  const reading = () => view().reading;
  const manifest = () => view().manifest;
  const draftBody = () => view().draftBody;
  const busy = () => view().activity.kind === "working";
  const noticeText = createMemo<string | null>(() => {
    const activity = view().activity;
    return activity.kind === "reported" || activity.kind === "failed" ? activity.text : null;
  });

  // 稿子换了：票据换对象，已选的块 id 不再指向任何东西。
  createEffect(() => {
    session.retarget({
      rootId: props.rootId,
      path: props.path,
      blocks: props.blocks,
      materials: props.materials,
    });
  });

  createEffect(() => {
    const seed = props.seed;
    if (seed !== undefined) session.seed(seed);
  });

  createEffect(() => {
    const initialPrompt = props.initialPrompt;
    if (initialPrompt !== undefined) session.proposePrompt(initialPrompt);
  });

  onMount(() => {
    void session.start();
    onCleanup(
      session.watchInFlight(POLL_INTERVAL_MS, (ms, task) => {
        const handle = window.setInterval(task, ms);
        return () => window.clearInterval(handle);
      }),
    );
  });

  return (
    <section class="dispatch" aria-label="派发">
      <header class="ticket">
        <div class="cell">
          <span class="name">段落</span>
          <span class="value">{cells().scope}</span>
        </div>
        <div class="cell">
          <span class="name">要求</span>
          <span class="value">{cells().requirement}</span>
        </div>
        <div class="cell">
          <span class="name">委托</span>
          <span class="value">{cells().agent}</span>
        </div>
        <div class="cell">
          <span class="name">范围</span>
          <span class="value">{cells().range}</span>
        </div>
        <div class="cell send">
          <button
            class="dispatch-send"
            type="button"
            disabled={!cells().ready || busy()}
            onClick={() => void session.send()}
          >
            送出
          </button>
        </div>
      </header>
      <Show when={noticeText()}>{(text) => <p class="notice">{text()}</p>}</Show>

      <Show when={model().phase.kind === "editing"}>
        <div class="blocks">
          <div class="blocks-head">
            <span>段落</span>
            <button
              type="button"
              class="dispatch-whole"
              onClick={() => session.selectWholeDocument()}
            >
              整章
            </button>
          </div>
          <For each={props.blocks}>
            {(block, index) => (
              <label class="block-row">
                <input
                  type="checkbox"
                  checked={model().selected.includes(block.id)}
                  onClick={(event) => {
                    event.preventDefault();
                    session.touchRow(index(), event.shiftKey);
                  }}
                  onKeyDown={(event) => {
                    if (event.key !== " " && event.key !== "Enter") return;
                    event.preventDefault();
                    session.touchRow(index(), event.shiftKey);
                  }}
                />
                <span class="ordinal">b{index() + 1}</span>
                <span class="peek">{block.text.slice(0, 20)}</span>
                <span class="count">{block.text.length} 字</span>
              </label>
            )}
          </For>
        </div>
        <Show when={props.materials.length > 0}>
          <div class="blocks">
            <div class="blocks-head">
              <span>资料</span>
            </div>
            <For each={props.materials}>
              {(material) => (
                <label class="material-row">
                  <input
                    type="checkbox"
                    checked={model().materialsSelected.includes(material.path)}
                    onChange={() => session.toggleMaterial(material.path)}
                  />
                  <span class="peek">{material.label}</span>
                </label>
              )}
            </For>
          </div>
        </Show>
        <Show when={model().agents.length > 0}>
          <div class="agent-row">
            <Show when={model().agents.length > 1}>
              <select
                class="dispatch-agent"
                value={model().agentId ?? ""}
                onChange={(event) => session.chooseAgent(event.currentTarget.value)}
              >
                <For each={model().agents}>
                  {(agent) => <option value={agent.id}>{agent.label}</option>}
                </For>
              </select>
            </Show>
            <span class="copies">
              <select
                class="dispatch-copies"
                aria-label="份数"
                value={String(model().copies)}
                onChange={(event) =>
                  session.chooseCopies(Number.parseInt(event.currentTarget.value, 10) as Copies)
                }
              >
                <option value="1">×1</option>
                <option value="2">并行 ×2</option>
                <option value="3">并行 ×3</option>
              </select>
            </span>
            <select
              class="dispatch-carry"
              aria-label="档位"
              value={model().carry}
              onChange={(event) => session.chooseCarry(event.currentTarget.value as CarryMode)}
            >
              <option value="diff">增量</option>
              <option value="full">全文</option>
              <option value="none">不带</option>
            </select>
            <Show when={reading()}>
              {(row) => (
                <span class="reading">
                  {row().rounds} 轮 · {row().stale ? "落后" : "同步"}
                </span>
              )}
            </Show>
          </div>
        </Show>
        <textarea
          class="dispatch-prompt"
          rows="4"
          placeholder="要求"
          value={model().prompt}
          onInput={(event) => session.proposePrompt(event.currentTarget.value)}
        />
      </Show>

      <Show when={model().drafts.length > 0}>
        <div class="blocks">
          <div class="blocks-head">
            <span>草稿</span>
          </div>
          <For each={model().drafts}>
            {(draft) => (
              <div class="draft-row">
                <div class="draft-line">
                  <span class="peek">{draft.title}</span>
                  <button
                    type="button"
                    class="draft-save"
                    disabled={busy()}
                    onClick={() => session.saveDraft(draft)}
                  >
                    保存
                  </button>
                  <button
                    type="button"
                    class="draft-edit"
                    disabled={busy()}
                    onClick={() => session.toggleDraftEdit(draft)}
                  >
                    改
                  </button>
                  <button
                    type="button"
                    class="draft-dismiss"
                    disabled={busy()}
                    onClick={() => session.dismissDraft(draft)}
                  >
                    退回
                  </button>
                </div>
                <Show
                  when={editingDraftId(model().draftEdit) === draft.id}
                  fallback={<span class="peek draft-peek">{draft.body.slice(0, 40)}</span>}
                >
                  <textarea
                    class="draft-body"
                    rows="6"
                    value={draftBody()?.body ?? ""}
                    onInput={(event) => session.editDraftBody(event.currentTarget.value)}
                  />
                </Show>
              </div>
            )}
          </For>
        </div>
      </Show>

      <Show when={manifest()}>
        {(phase) => (
          <div class="manifest">
            <p class="manifest-title">清单 · {phase().preview.digest.slice(0, 12)}</p>
            <For each={phase().preview.manifest}>
              {(entry) => (
                <div class="manifest-row">
                  <span class="section">
                    {entry.section} · {entry.source}
                  </span>
                  <span class="bytes">{entry.bytes} B</span>
                  <span class="tokens">{tokenLabel(entry.tokens)}</span>
                </div>
              )}
            </For>
            <button type="button" class="dispatch-expand" onClick={() => session.toggleReveal()}>
              {phase().reveal.kind === "request" ? "收" : "原文"}
            </button>
            <Show when={phase().reveal.kind === "request"}>
              <pre class="request-md">{phase().preview.requestMd}</pre>
            </Show>
            <div class="actions">
              <button
                class="primary dispatch-authorize"
                type="button"
                disabled={busy()}
                onClick={() => void session.authorize()}
              >
                授权
              </button>
              <button type="button" disabled={busy()} onClick={() => session.newTask()}>
                返回
              </button>
            </div>
          </div>
        )}
      </Show>

      <Show when={runs().length > 0}>
        <div class="runs">
          <For each={runs()}>
            {(run) => (
              <div class="run-row">
                <span class="status">{runStatusLabel(run)}</span>
                <Show when={run.workspace}>
                  <code class="workspace">{run.workspace}</code>
                </Show>
                <span class="run-actions">
                  <Show when={run.progress === "dispatched"}>
                    <button
                      class="dispatch-collect"
                      type="button"
                      disabled={busy()}
                      onClick={() => session.collect(run)}
                    >
                      收取
                    </button>
                  </Show>
                  <Show when={run.progress === "failed" || run.progress === "cancelled"}>
                    <button
                      class="dispatch-retry"
                      type="button"
                      disabled={busy()}
                      onClick={() => session.retry(run)}
                    >
                      重试
                    </button>
                  </Show>
                  <Show when={!terminal(run)}>
                    <button type="button" disabled={busy()} onClick={() => session.cancel(run)}>
                      取消
                    </button>
                  </Show>
                </span>
              </div>
            )}
          </For>
        </div>
      </Show>

      <button type="button" class="dispatch-close" onClick={() => props.onClosed?.()}>
        收起
      </button>
      <Show when={model().phase.kind === "dispatched"}>
        <button type="button" class="dispatch-new" onClick={() => session.newTask()}>
          再发
        </button>
      </Show>
    </section>
  );
}

// apps/desktop/src/shell/DispatchSurface.vue
<script setup lang="ts">
// biome-ignore-all lint/correctness/noUnusedVariables: bindings used only in
// the template are real usage; biome does not parse Vue templates.
// The dispatch ticket (SPEC 9.6): scope → prompt → agent → range → send, the
// manifest the author reads, the click that authorizes, and manual return.
// Nothing here derives state Rust owns; every fact comes
// back over the bridge.

import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { describe, unwrap } from "../bridge";
import {
  type AgentReadingDto,
  type BlockDto,
  type CarryMode,
  commands,
  type DispatchPreviewDto,
  type DocumentRow,
  type HostStateDto,
  type MaterialDraftRow_Serialize,
  type RunDto,
} from "../generated/bindings.gen";

const props = defineProps<{
  rootId: string;
  path: string;
  blocks: BlockDto[];
  materials: { path: string; label: string }[];
  /** Block ids planted by the editor's context menu (派发此段 / 加入派发). */
  seed?: string[];
}>();

const emit = defineEmits<{
  collected: [count: number];
  materialSaved: [row: DocumentRow];
  closed: [];
}>();

type Phase = { kind: "editing" } | { kind: "previewing" } | { kind: "dispatched" };

const selected = ref<Set<string>>(new Set());
const materialsSelected = ref<Set<string>>(new Set());
const prompt = ref("");
const agentId = ref<string | null>(null);
const agents = ref<{ id: string; label: string }[]>([]);
const copies = ref(1);
const carry = ref<CarryMode>("diff");
const taskId = ref<string | null>(null);
const phase = ref<Phase>({ kind: "editing" });
const preview = ref<DispatchPreviewDto | null>(null);
const host = ref<HostStateDto | null>(null);
const ledger = ref<AgentReadingDto[]>([]);
const drafts = ref<MaterialDraftRow_Serialize[]>([]);
const editingDraft = ref<string | null>(null);
const editedBody = ref("");
const notice = ref<string | null>(null);
const busy = ref(false);
const showRequest = ref(false);
let poll: number | null = null;

const fail = (error: unknown): void => {
  notice.value = describe(error);
};

const scopeIds = computed<string[]>(() =>
  props.blocks.filter((block) => selected.value.has(block.id)).map((block) => block.id),
);

// The five cells (SPEC 9.6): each shows its value when met, — when not, and
// only the first blocker speaks.
const cells = computed(() => {
  const scope = selected.value.size;
  const requirement = prompt.value.trim().length;
  const agent = agents.value.find((candidate) => candidate.id === agentId.value) ?? null;
  return {
    scope: scope > 0 ? `${scope} 块` : "—",
    requirement: requirement > 0 ? `${requirement} 字` : "—",
    agent: agent ? agent.label : "—",
    range: scope > 0 ? `所选 ${scope} 块` : "—",
    ready: scope > 0 && requirement > 0 && agent,
  };
});

const runs = computed<RunDto[]>(() => {
  if (!host.value) return [];
  const taskIds = new Set(
    host.value.tasks.filter((task) => task.document === props.path).map((task) => task.id),
  );
  return host.value.runs.filter((run) => taskIds.has(run.taskId));
});

const refresh = async (): Promise<void> => {
  try {
    host.value = await unwrap(commands.hostState(props.rootId));
    drafts.value = await unwrap(commands.listMaterialDrafts(props.rootId));
    ledger.value = await unwrap(commands.agentReadingLedger(props.rootId));
  } catch (error) {
    fail(error);
  }
};

// The ticket's top hint (C12): what the picked agent has read of this
// document, and whether the manuscript has moved since.
const reading = computed<AgentReadingDto | null>(
  () =>
    ledger.value.find((row) => row.agentId === agentId.value && row.document === props.path) ??
    null,
);

const toggle = (id: string): void => {
  const next = new Set(selected.value);
  if (next.has(id)) next.delete(id);
  else next.add(id);
  selected.value = next;
};

// Shift-click walks the range between the last touched row and this one —
// the only way a 100+ block chapter stays selectable by hand.
let lastTouched = -1;
const touchRow = (index: number, event: MouseEvent): void => {
  const block = props.blocks[index];
  if (block === undefined) return;
  if (event.shiftKey && lastTouched >= 0 && lastTouched !== index) {
    const [from, to] = [Math.min(lastTouched, index), Math.max(lastTouched, index)];
    const next = new Set(selected.value);
    for (let i = from; i <= to; i += 1) {
      const entry = props.blocks[i];
      if (entry !== undefined) next.add(entry.id);
    }
    selected.value = next;
  } else {
    toggle(block.id);
  }
  lastTouched = index;
};

const toggleMaterial = (path: string): void => {
  const next = new Set(materialsSelected.value);
  if (next.has(path)) next.delete(path);
  else next.add(path);
  materialsSelected.value = next;
};

const materialPaths = computed<string[]>(() =>
  props.materials
    .filter((material) => materialsSelected.value.has(material.path))
    .map((material) => material.path),
);

const wholeChapter = (): void => {
  selected.value = new Set(props.blocks.map((block) => block.id));
};

const send = async (): Promise<void> => {
  if (!cells.value.ready || busy.value) return;
  busy.value = true;
  notice.value = null;
  try {
    const task = await unwrap(
      commands.draftReviewTask(props.rootId, props.path, prompt.value.trim()),
    );
    taskId.value = task.id;
    preview.value = await unwrap(
      commands.previewDispatch(
        props.rootId,
        props.path,
        scopeIds.value,
        materialPaths.value,
        prompt.value.trim(),
        agentId.value as string,
        carry.value,
      ),
    );
    phase.value = { kind: "previewing" };
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

const authorize = async (): Promise<void> => {
  if (!preview.value || !taskId.value || !agentId.value || busy.value) return;
  busy.value = true;
  notice.value = null;
  try {
    const runs = await unwrap(
      commands.authorizeDispatch({
        rootId: props.rootId,
        taskId: taskId.value,
        path: props.path,
        blockIds: scopeIds.value,
        materialPaths: materialPaths.value,
        prompt: prompt.value.trim(),
        clickedDigest: preview.value.digest,
        newAgents: Array.from({ length: copies.value }, () => agentId.value as string),
        retryRunIds: [],
        agentId: agentId.value,
        carry: carry.value,
      }),
    );
    for (const run of runs) {
      await unwrap(commands.launchRun(props.rootId, run.id));
    }
    preview.value = null;
    phase.value = { kind: "dispatched" };
    notice.value =
      runs.length > 1
        ? `已发出 · 并行 ×${runs.length}`
        : `已发出 → ${runs[0]?.workspace ?? "runs/"}`;
    await refresh();
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

const newTask = (): void => {
  phase.value = { kind: "editing" };
  taskId.value = null;
  preview.value = null;
  selected.value = new Set();
  prompt.value = "";
  notice.value = null;
};

const collect = async (run: RunDto): Promise<void> => {
  if (busy.value) return;
  busy.value = true;
  notice.value = null;
  try {
    const outcome = await unwrap(commands.collectAttempt(props.rootId, run.id));
    if (outcome.kind === "waiting") {
      notice.value = "未回";
    } else if (outcome.kind === "completed") {
      const got = outcome.value;
      notice.value =
        got.drafts > 0
          ? `已收 · ${got.proposals} 提案 · ${got.drafts} 草稿`
          : `已收 · ${got.proposals} 提案`;
      emit("collected", got.proposals);
    } else {
      notice.value = `失败 · ${outcome.value.code}`;
    }
    await refresh();
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

const retry = async (run: RunDto): Promise<void> => {
  if (busy.value || !agentId.value) return;
  busy.value = true;
  notice.value = null;
  try {
    const queued = await unwrap(commands.retryRun(props.rootId, run.id));
    const again = await unwrap(
      commands.previewDispatch(
        props.rootId,
        props.path,
        scopeIds.value,
        materialPaths.value,
        prompt.value.trim(),
        agentId.value as string,
        carry.value,
      ),
    );
    await unwrap(
      commands.authorizeDispatch({
        rootId: props.rootId,
        taskId: queued.taskId,
        path: props.path,
        blockIds: scopeIds.value,
        materialPaths: materialPaths.value,
        prompt: prompt.value.trim(),
        clickedDigest: again.digest,
        newAgents: [],
        retryRunIds: [queued.id],
        agentId: agentId.value,
        carry: carry.value,
      }),
    );
    await unwrap(commands.launchRun(props.rootId, queued.id));
    notice.value = "已重发";
    await refresh();
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

const cancel = async (run: RunDto): Promise<void> => {
  if (busy.value) return;
  busy.value = true;
  try {
    await unwrap(commands.cancelRun(props.rootId, run.id));
    await refresh();
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

// A draft becomes a Material only through these two clicks (SPEC 8.7): save
// (as written or after the author's own edit) or dismiss. Nothing else may.
const saveDraft = async (draft: MaterialDraftRow_Serialize): Promise<void> => {
  if (busy.value) return;
  busy.value = true;
  notice.value = null;
  try {
    const body = editingDraft.value === draft.id ? editedBody.value : null;
    const row = await unwrap(commands.commitMaterialAction(props.rootId, draft.id, body, false));
    if (row !== null) emit("materialSaved", row);
    editingDraft.value = null;
    notice.value = "已存";
    await refresh();
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

const dismissDraft = async (draft: MaterialDraftRow_Serialize): Promise<void> => {
  if (busy.value) return;
  busy.value = true;
  notice.value = null;
  try {
    await unwrap(commands.commitMaterialAction(props.rootId, draft.id, null, true));
    if (editingDraft.value === draft.id) editingDraft.value = null;
    notice.value = "已退";
    await refresh();
  } catch (error) {
    fail(error);
  } finally {
    busy.value = false;
  }
};

const startEdit = (draft: MaterialDraftRow_Serialize): void => {
  editingDraft.value = draft.id;
  editedBody.value = draft.body;
};

const tokenLabel = (tokens: { kind: string; value?: number }): string => {
  if (tokens.kind === "actual") return `token 实报 ${tokens.value}`;
  if (tokens.kind === "estimated") return `token 预估约 ${tokens.value}`;
  return "token 未知";
};

const runStatusLabel = (run: RunDto): string => {
  const labels: Record<string, string> = {
    queued: "排队",
    authorized: "已授权",
    launching: "启动",
    dispatched: "在途",
    completed: "完成",
    failed: `失败：${run.failure ?? ""}`,
    cancelled: "取消",
  };
  return labels[run.progress] ?? run.progress;
};

onMounted(async () => {
  // The context menu's 派发此段 / 加入派发 plants block ids here.
  if (props.seed !== undefined && props.seed.length > 0) {
    selected.value = new Set([...selected.value, ...props.seed]);
  }
  try {
    // Only named writing partners enter the ticket. A machine connection is
    // not an Agent; manual return remains the explicit fallback.
    for (const agent of await commands.listAgents()) {
      agents.value.push({
        id: agent.id,
        label: `${agent.name} · ${agent.channel}`,
      });
    }
    const l0 = await commands.l0FileChannelAgent();
    agents.value.push({ id: l0, label: "手动往返" });
    agentId.value = agents.value[0]?.id ?? l0;
  } catch (error) {
    fail(error);
  }
  await refresh();
  // In-flight runs settle off-thread; while any exist, poll the journal.
  poll = window.setInterval(() => {
    if (
      host.value?.runs.some((run) =>
        ["authorized", "launching", "dispatched"].includes(run.progress),
      )
    ) {
      void refresh();
    }
  }, 2_500);
});

onUnmounted(() => {
  if (poll !== null) window.clearInterval(poll);
});

// 加入派发 may arrive after the panel is already open.
watch(
  () => props.seed,
  (seed) => {
    if (seed !== undefined && seed.length > 0) {
      selected.value = new Set([...selected.value, ...seed]);
    }
  },
);
</script>

<template>
  <section class="dispatch" aria-label="派发">
    <header class="ticket">
      <div class="cell"><span class="name">段落</span><span class="value">{{ cells.scope }}</span></div>
      <div class="cell"><span class="name">要求</span><span class="value">{{ cells.requirement }}</span></div>
      <div class="cell"><span class="name">委托</span><span class="value">{{ cells.agent }}</span></div>
      <div class="cell"><span class="name">范围</span><span class="value">{{ cells.range }}</span></div>
      <div class="cell send">
        <button
          class="dispatch-send"
          type="button"
          :disabled="!cells.ready || busy"
          @click="send"
        >
          送出
        </button>
      </div>
    </header>
    <p v-if="notice" class="notice">{{ notice }}</p>

    <template v-if="phase.kind === 'editing'">
      <div class="blocks">
        <div class="blocks-head">
          <span>段落</span>
          <button type="button" class="dispatch-whole" @click="wholeChapter">整章</button>
        </div>
        <label v-for="(block, index) in blocks" :key="block.id" class="block-row" @click.prevent="touchRow(index, $event)">
          <input
            type="checkbox"
            :checked="selected.has(block.id)"
            @click.prevent
          />
          <span class="ordinal">b{{ index + 1 }}</span>
          <span class="peek">{{ block.text.slice(0, 20) }}</span>
          <span class="count">{{ block.text.length }} 字</span>
        </label>
      </div>
      <div class="blocks" v-if="materials.length > 0">
        <div class="blocks-head"><span>资料</span></div>
        <label v-for="material in materials" :key="material.path" class="material-row">
          <input
            type="checkbox"
            :checked="materialsSelected.has(material.path)"
            @change="toggleMaterial(material.path)"
          />
          <span class="peek">{{ material.label }}</span>
        </label>
      </div>
      <div class="agent-row" v-if="agents.length > 0">
        <select v-if="agents.length > 1" v-model="agentId" class="dispatch-agent">
          <option v-for="agent in agents" :key="agent.id" :value="agent.id">{{ agent.label }}</option>
        </select>
        <span class="copies">
          <select v-model.number="copies" class="dispatch-copies" aria-label="份数">
            <option :value="1">×1</option>
            <option :value="2">并行 ×2</option>
            <option :value="3">并行 ×3</option>
          </select>
        </span>
        <select v-model="carry" class="dispatch-carry" aria-label="档位">
          <option value="diff">增量</option>
          <option value="full">全文</option>
          <option value="none">不带</option>
        </select>
        <span v-if="reading" class="reading">
          {{ reading.rounds }} 轮 · {{ reading.stale ? "落后" : "同步" }}
        </span>
      </div>
      <textarea
        v-model="prompt"
        class="dispatch-prompt"
        rows="4"
        placeholder="要求"
      ></textarea>
    </template>

    <div class="blocks" v-if="drafts.length > 0">
      <div class="blocks-head"><span>草稿</span></div>
      <div v-for="draft in drafts" :key="draft.id" class="draft-row">
        <div class="draft-line">
          <span class="peek">{{ draft.title }}</span>
          <button type="button" class="draft-save" :disabled="busy" @click="saveDraft(draft)">
            保存
          </button>
          <button
            type="button"
            class="draft-edit"
            :disabled="busy"
            @click="editingDraft === draft.id ? (editingDraft = null) : startEdit(draft)"
          >
            改
          </button>
          <button type="button" class="draft-dismiss" :disabled="busy" @click="dismissDraft(draft)">
            退回
          </button>
        </div>
        <textarea
          v-if="editingDraft === draft.id"
          v-model="editedBody"
          class="draft-body"
          rows="6"
        ></textarea>
        <span v-else class="peek draft-peek">{{ draft.body.slice(0, 40) }}</span>
      </div>
    </div>

    <template v-else-if="phase.kind === 'previewing' && preview">
      <div class="manifest">
        <p class="manifest-title">清单 · {{ preview.digest.slice(0, 12) }}</p>
        <div v-for="entry in preview.manifest" :key="entry.section + entry.source" class="manifest-row">
          <span class="section">{{ entry.section }} · {{ entry.source }}</span>
          <span class="bytes">{{ entry.bytes }} B</span>
          <span class="tokens">{{ tokenLabel(entry.tokens) }}</span>
        </div>
        <button type="button" class="dispatch-expand" @click="showRequest = !showRequest">
          {{ showRequest ? "收" : "原文" }}
        </button>
        <pre v-if="showRequest" class="request-md">{{ preview.requestMd }}</pre>
        <div class="actions">
          <button class="primary dispatch-authorize" type="button" :disabled="busy" @click="authorize">
            授权
          </button>
          <button type="button" :disabled="busy" @click="phase = { kind: 'editing' }">返回</button>
        </div>
      </div>
    </template>

    <template v-if="runs.length > 0">
      <div class="runs">

        <div v-for="run in runs" :key="run.id" class="run-row">
          <span class="status">{{ runStatusLabel(run) }}</span>
          <code v-if="run.workspace" class="workspace">{{ run.workspace }}</code>
          <span class="run-actions">
            <button
              v-if="run.progress === 'dispatched'"
              class="dispatch-collect"
              type="button"
              :disabled="busy"
              @click="collect(run)"
            >
              收取
            </button>
            <button
              v-if="run.progress === 'failed' || run.progress === 'cancelled'"
              class="dispatch-retry"
              type="button"
              :disabled="busy"
              @click="retry(run)"
            >
              重试
            </button>
            <button
              v-if="run.progress !== 'completed' && run.progress !== 'failed' && run.progress !== 'cancelled'"
              type="button"
              :disabled="busy"
              @click="cancel(run)"
            >
              取消
            </button>
          </span>
        </div>
      </div>
    </template>

    <button type="button" class="dispatch-close" @click="emit('closed')">收起</button>
    <button v-if="phase.kind === 'dispatched'" type="button" class="dispatch-new" @click="newTask">
      再发
    </button>
  </section>
</template>

<style>
.dispatch {
  border-left: 1px solid var(--rule);
  background: var(--paper-raised);
  padding: 12px 16px;
  font-size: 13px;
  max-width: 520px;
  min-width: 360px;
  overflow-y: auto;
}

.ticket {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 6px;
  margin-bottom: 8px;
}

.cell {
  border: 1px solid var(--rule);
  border-radius: 3px;
  padding: 6px 8px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.cell .name {
  color: var(--ink-faint);
  font-size: 11px;
}

.cell .value {
  font-variant-numeric: tabular-nums;
}

.cell.send {
  padding: 0;
  border: none;
}

/* 送出是人的行动：全票唯一允许醒目的控件。 */
.dispatch-send {
  all: unset;
  cursor: pointer;
  text-align: center;
  width: 100%;
  height: 100%;
  box-sizing: border-box;
  padding: 6px 8px;
  border-radius: 3px;
  border: 1px solid color-mix(in oklab, var(--seal) 45%, transparent);
  color: var(--seal);
  background: var(--seal-wash);
}

.dispatch-send:hover:not(:disabled) {
  border-color: var(--seal);
}

.dispatch-send:disabled {
  opacity: 0.35;
  cursor: default;
}

.notice {
  color: var(--pending);
}

.blocks {
  margin: 8px 0;
  max-height: 40vh;
  overflow-y: auto;
  border-top: 1px solid var(--rule);
}

.blocks-head {
  display: flex;
  justify-content: space-between;
  padding: 6px 0;
  color: var(--ink-faint);
}

.block-row {
  display: flex;
  gap: 8px;
  align-items: baseline;
  padding: 3px 0;
  cursor: pointer;
}

.block-row .ordinal {
  color: var(--ink-ghost);
  font-variant-numeric: tabular-nums;
}

.block-row .peek {
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.block-row .count {
  color: var(--ink-ghost);
  font-variant-numeric: tabular-nums;
}

.material-row {
  display: flex;
  gap: 8px;
  align-items: baseline;
  padding: 3px 0;
  cursor: pointer;
}

.material-row .peek {
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.draft-row {
  padding: 3px 0;
}

.draft-line {
  display: flex;
  gap: 8px;
  align-items: baseline;
}

.draft-line .peek {
  flex: 1;
}

.draft-peek {
  display: block;
  color: var(--ink-ghost);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.draft-body {
  width: 100%;
  box-sizing: border-box;
  font: inherit;
  padding: 8px;
  border: 1px solid var(--rule);
  border-radius: 3px;
  background: transparent;
  color: inherit;
  resize: vertical;
}

.dispatch-prompt {
  width: 100%;
  box-sizing: border-box;
  font: inherit;
  padding: 8px;
  border: 1px solid var(--rule);
  border-radius: 3px;
  background: transparent;
  color: inherit;
  resize: vertical;
}

.agent-row {
  display: flex;
  gap: 8px;
  align-items: baseline;
  margin: 8px 0;
}

.reading {
  margin-left: auto;
  color: var(--ink-faint);
  font-variant-numeric: tabular-nums;
}

.dispatch-agent {
  font: inherit;
  background: transparent;
  color: inherit;
  border: 1px solid var(--rule);
  border-radius: 3px;
  padding: 4px 8px;
}

.dispatch-carry {
  font: inherit;
  background: transparent;
  color: inherit;
  border: 1px solid var(--rule);
  border-radius: 3px;
  padding: 4px 8px;
}

.manifest {
  margin: 8px 0;
}

.manifest-title {
  font-size: 12px;
  color: var(--ink-faint);
}

.manifest-row {
  display: flex;
  gap: 12px;
  padding: 3px 0;
  font-variant-numeric: tabular-nums;
}

.manifest-row .section {
  flex: 1;
}

.request-md {
  max-height: 30vh;
  overflow: auto;
  font-size: 12px;
  padding: 8px;
  border: 1px solid var(--rule);
  white-space: pre-wrap;
}

.actions {
  display: flex;
  gap: 8px;
  margin-top: 8px;
}

.runs {
  margin-top: 12px;
  border-top: 1px solid var(--rule);
}

.runs-title {
  font-size: 12px;
  color: var(--ink-faint);
}

.run-row {
  display: flex;
  gap: 8px;
  align-items: baseline;
  padding: 4px 0;
}

.run-row .status {
  flex: 1;
}

.run-row .workspace {
  font-size: 11px;
  color: var(--ink-faint);
}

.run-actions {
  display: flex;
  gap: 6px;
}

.dispatch-close {
  margin-top: 12px;
  color: var(--ink-faint);
}
</style>
